### ISSUE TITLE
AllowMixedWeaponTypes!Buged?

### ISSUE THREAD

**Issue by irgc** [Rochet2/TrinityCore#73] opened 2018-03-06 01:09 UTC
Hi @Rochet

Can not transmog weapons illidan  [Warglaive of Azzinoth] -  [Warglaive of Azzinoth]

to  onehands or daggers! 

just can to use main and off hand for transmog.

i allowed mixed weapons

What should I do?

trinitycore 3.3.5 last

windows 2010 server

**Comment by Rochet2** [comment] 2018-03-06 11:59
Can you give the item entry you used as source of transmogrification and as the target of transmogrification?

**Comment by irgc** [comment] 2018-03-06 13:14
transmog items [Warglaive of Azzinoth] main hand and off hand -> id items 32837 & 32838

I want to be trasmog 
All one hands - daggers - maces - axes


but just can to use main and off hand for transmog!

**Comment by Rochet2** [comment] 2018-03-06 17:46
Warglaives are legendary items. Did you set `Transmogrification.AllowLegendary = 1`?

You did not post what items you used. But depending on what items you try you may need to ignore some requirements by for example setting `Transmogrification.IgnoreReqStats = 1`

As you can see here, AllowMixedWeaponTypes is not related to "one hand" and "main hand" and "off-hand":

>Transmogrification.AllowMixedWeaponTypes`
>    Description: Allow **axe** to be transmogrified with **dagger** for example

Main and off-hand weapon models are designed so that they only fit off hand or main hand specifically.
The current code does not allow using off hand in main hand or the other way around.
Examples:
http://www.wowhead.com/item=6691/swinetusk-shank cannot look like http://www.wowhead.com/item=32837/warglaive-of-azzinoth since swinetusk shank is one hand and could be equipped to off hand while looking like a main hand weapon.

http://www.wowhead.com/item=32837/warglaive-of-azzinoth can look like http://www.wowhead.com/item=6691/swinetusk-shank since swinetusk shank is one hand and can be used on main hands, off hands and one hand.

**Comment by irgc** [comment] 2018-03-06 19:01
Transmogrification.AllowUncommon = 1
Transmogrification.AllowRare = 1
Transmogrification.AllowEpic = 1
Transmogrification.AllowLegendary = 1
Transmogrification.AllowHeirloom = 1
Transmogrification.AllowMixedWeaponTypes = 1
Transmogrification.IgnoreReqStats = 1


Not work to transmog main hand or off hands by one hands and swords

**Comment by Rochet2** [comment] 2018-03-06 20:02
> Not work transmog main hand or off hand
> to
> one hand and swords - axe - mace- daggers

Need item entries.. pls. item entries.
Entries of the items you use and test with.

I know it works on my end.

**Comment by irgc** [comment] 2018-03-07 00:26
item ids for transmog : 50736- 50672 - 50654

**Comment by Rochet2** [comment] 2018-03-07 13:10
You must be able to equip the item you transmogrify to.
Is your character able to equip those items? (Is he level 80? Has the Daggers, Swords, Axes skill?)

**Comment by irgc** [comment] 2018-03-07 14:06
see image not found on menu transmog list

icant transmog to my daggers!

[Warglaive of Azzinoth] ! id 32837 & 32838

https://imgur.com/a/aLTdF

**Comment by Rochet2** [comment] 2018-03-07 14:23
> icant transmog to my daggers!

From all messages I always understood you tried to transmogrify warglaives to some other look, but this was never the case.

> see image not found on menu transmog list

There exist no setting to enable this. I already explained before that this is intended behavior:

> Main and off-hand weapon **_models_** are designed so that they **_only fit off hand or main hand_** specifically.
> The current code **_does not allow using off hand in main hand_** or the other way around.

> http://www.wowhead.com/item=6691/swinetusk-shank _**cannot look like**_ http://www.wowhead.com/item=32837/warglaive-of-azzinoth since **_swinetusk shank is one hand_** and **_could be equipped to off hand while looking like a main hand weapon_**.

Duplicate of https://github.com/Rochet2/TrinityCore/issues/2
Closing.

**Closed by Rochet2** 2018-03-07 14:23 UTC
