### ISSUE TITLE
Update level 255

### ISSUE THREAD

**Issue by Hir0shi** [Rochet2/TrinityCore#96] opened 2018-11-10 06:48 UTC
Hi @Rochet2 

in my server i creat item custom and can't use item to transmoge!

example item one hand:

`
INSERT INTO item_template VALUES (270000, 2, 15, -1, '|cffFACC2EDagger', 6555, 0, 0, 0, 1, 0, 0, 13, -1, -1, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 10, 3, 25000, 4, 410000, 7, 410000, 1, 25000, 36, 1200, 44, 16000, 3, 25000, 32, 6000, 38, 30000, 45, 30000, 0, 0, 28500, 35500, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 1800, 0, 0, 20262, 1, 0, 0, 0, 0, 0, 19255, 1, 0, 0, 0, 0, 0, 71188, 1, 0, 0, 0, 0, 0, 26615, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, '|cffbbbbbbMade test', 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'internalitemhanler', 0, 0, 0, 0, 0, 0);
`

how to fixed?
please...

**Comment by Rochet2** [comment] 2018-11-10 08:35
Can you provide information about the item you try to transmogrify **and** the item you try to use as source of transmogrification?
What are your settings for transmogrification system?
What character (race, class, level) you try to transmog the item with.

I tested and with all requirements off in the transmog config the item works just fine, so the problem is with the config restricting it very likely.

**Comment by Hir0shi** [comment] 2018-11-10 08:57
oh sry please again test item custom update, for this'|cffFACC2EDagger' color name!

and this is my transmog/conf

Transmogrification.AllowPoor = 0
Transmogrification.AllowCommon = 0
Transmogrification.AllowUncommon = 1
Transmogrification.AllowRare = 1
Transmogrification.AllowEpic = 1
Transmogrification.AllowLegendary = 1
Transmogrification.AllowArtifact = 1
Transmogrification.AllowHeirloom = 1

Transmogrification.AllowMixedArmorTypes = 1
Transmogrification.AllowMixedWeaponTypes = 1
Transmogrification.AllowMixedInventoryTypes = 1
Transmogrification.AllowFishingPoles = 1

Transmogrification.IgnoreReqRace = 1
Transmogrification.IgnoreReqClass = 1
Transmogrification.IgnoreReqSkill = 1
Transmogrification.IgnoreReqSpell = 1
Transmogrification.IgnoreReqLevel = 1
Transmogrification.IgnoreReqEvent = 1
Transmogrification.IgnoreReqStats = 1

**Comment by Rochet2** [comment] 2019-01-22 21:00
no reply for months, closing

**Closed by Rochet2** 2019-01-22 21:00 UTC
