### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by ahg1995** [Rochet2/TrinityCore#130] opened 2021-01-26 23:24 UTC
**Description:**

When compiling the core i get following errors:

error C3668: 'NPC_TransmogDisplayVendor::TransmogVendorAI::GossipHello': method with override specifier 'override' did not override any base class methods
-
error C4263: 'bool NPC_TransmogDisplayVendor::TransmogVendorAI::OnGossipHello(Player *,Creature *)': member function does not override any base class virtual member function
-
error C4264: 'bool CreatureAI::OnGossipHello(Player *)': no override available for virtual member function from base 'CreatureAI'; function is hidden
-
error C3668: 'NPC_TransmogDisplayVendor::TransmogVendorAI::GossipSelect': method with override specifier 'override' did not override any base class methods
-
error C4263: 'bool NPC_TransmogDisplayVendor::TransmogVendorAI::OnGossipSelect(Player *,Creature *,uint32,uint32)': member function does not override any base class virtual member function
-
error C4264: 'bool CreatureAI::OnGossipSelect(Player *,uint32,uint32)': no override available for virtual member function from base 'CreatureAI'; function is hidden

.

**Current behaviour:**

Compiled with errors.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Should work fine.

**Steps to reproduce the problem:**

1. git apply transmog.diff.  
2. cmake
3. compile

**Branch(es):**

3.5.5

**TC rev. latest:** 

**TDB version:**  Trinitycore 3.5.5 latest rev

**Operating system:** Windows

**Comment by Rochet2** [comment] 2021-03-07 14:44
CI now passes. I assume the issue is now fixed.
Open a new ticket or comment here if the issue persists.

**Closed by Rochet2** 2021-03-07 14:44 UTC
