### ISSUE TITLE
Can't delete gameobjects

### ISSUE THREAD

**Issue by Draakoor** [Rochet2/TrinityCore#58] opened 2017-08-03 23:25 UTC
**Description**: I installed Eluna with objscale, aio, playeritemgossip, multivendor, dressnpcs, item enchant visiauls, gomove, reforging and transmog. I can't move any gameobject or delete it. I just get the message gameobject (guid=number) not found

**Current behaviour**: I can't delete gameobjects

**Expected behaviour**: Gameobjects should be deleted

**Steps to reproduce the problem**:

1. Installed Trinity Eluna Wotlk
2. Objscale
3. Playeritem Gossip
4. Multivendor
5. Dressnpcs
6. Gomove
7. Reforging
8. Transmog
9. AIO
10. Item visual enchants

**Branch(es)**: 335

**TC hash/commit**:  Lastest Eluna

**TDB version**:  Lastest Eluna

**Operating system**:  Windows Server 2k12 R2

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rochet2** [comment] 2017-08-04 14:37
Are you deleting gameobjects with .gob del <guid> or through gomove or some other way?

The issue is probably caused by https://github.com/TrinityCore/TrinityCore/pull/19056 that was merged recently and broke either one or more of the scripts or then it broke the GM commands for gameobjects.

**Comment by Draakoor** [comment] 2017-08-04 14:55
I tired to delete it with .gob del and through gomove, also through trinity gamemaster helper and trinity admin. Not worked.

**Comment by Rochet2** [comment] 2017-08-04 18:21
Actual error message: "Game Object (GUID: %u) not found".

@Draakoor Where did you get the guid from that you use for .gob del?

**Comment by Draakoor** [comment] 2017-08-04 20:20
Through .gob near
For example:
166014
166015
166016

**Closed** 2017-08-04 23:27 UTC
Labels: bug
